build:
  cache:
        directories:
            - node_modules/  # Without prefix, the path is relative to your repository root.

    tests:
        override:
            - ./bin/install-wp-tests.sh wordpress_test root ''
            -
                command: 'phpunit --coverage-clover=processing-coverage'
                coverage:
                    file: 'processing-coverage'
                    format: 'php-clover'
