build:
    environment:
        php:
            version: 5.5.36
    cache:
        directories:
            - node_modules/
            - vendor/

    dependencies:
        after:
            - npm install -g gulp

    tests:
        before:
            - gulp
            - gulp lint
            - ./bin/install-wp-tests.sh wordpress_test root ''
        override:
            - gulp phpunit-single
            - gulp phpunit-multisite
            -
                command: 'gulp phpunit-codecoverage'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
