language: php

branches:
  only:
    - master

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.6 WP_MULTISITE=0

matrix:
  exclude:
    - php: '7.1'
      env: WP_VERSION=4.6 WP_MULTISITE=0

before_script:
  - nvm install node
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - npm install -g gulp
  - npm install

script:
  - gulp lint
  - phpunit -c codecoverage.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover coverage.clover
